name: Testing

on:
  pull_request_review:
    branches:
        - main
  push:
    branches:
      - main


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install flex bison
      run: sudo apt-get install build-essential 
    - name: Install update
      run:  sudo apt-get update
    - name: Install valgrind
      run: sudo apt-get install valgrind
      
    - name: Make tin
      run: make tin
    
    - name: Memory leak check
      run: valgrind --leak-check=full --track-origins=yes ./build/tin example.tin
    
    - name: Working Test
      run: ./build/tin units/working.tin
      if: units/working.tin.ast.json != NULL
    - name: Typecheck Test
      run: ./build/tin units/typecheck-test.tin
    - name: Missing Semicolon Test
           ./build/tin units/missing-semicolon.tin
    - name: Missing Arguement Test
           ./build/tin units/missing-arguement.tin
    - name: Redefined Variable Test
           ./build/tin units/redefined-variable.tin
    - name: Undefined Variable Test
           ./build/tin units/undefined-variable.tin
           

